CREATE DATABASE IF NOT EXISTS login;
CREATE TABLE IF NOT EXISTS StudentLogin ( ROLL VARCHAR(50) PRIMARY KEY, NAME VARCHAR(100) NOT NULL, PASSWORD VARCHAR(100) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- INSERT INTO StudentLogin (ROLL, NAME, PASSWORD) VALUES ("..", "..", "..");
CREATE TABLE IF NOT EXISTS TeacherLogin ( TID VARCHAR(50) PRIMARY KEY, NAME VARCHAR(100) NOT NULL, PASSWORD VARCHAR(100) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- INSER INTO TeacherLogin (TID, NAME, PASSWORD) VALUES ("..", "..", "..");
