CREATE DATABASE IF NOT EXISTS login;
CREATE TABLE IF NOT EXISTS StudentLogin ( ROLL VARCHAR(50) PRIMARY KEY, NAME VARCHAR(100) NOT NULL, PASSWORD VARCHAR(100) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- INSERT INTO StudentLogin (ROLL, NAME, PASSWORD) VALUES ("..", "..", "..");
CREATE TABLE IF NOT EXISTS TeacherLogin ( TID VARCHAR(50) PRIMARY KEY, NAME VARCHAR(100) NOT NULL, PASSWORD VARCHAR(100) NOT NULL, CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
-- INSERT INTO TeacherLogin (TID, NAME, PASSWORD) VALUES ("..", "..", "..");
CREATE TABLE IF NOT EXISTS ST_NOTICE (DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONTENT VARCHAR(300));
-- INSERT INTO ST_NOTICE (CONTENT) VALUES (".................................");
